schemaVersion: 2.0
timeout: 150

notify:
  pullRequestComment:
    postOnSuccess: false

machine:
  env:
    RUNTIME_JDK_VERSION: 17
    skipTest: false
    CODE_VERSION: $(./code_version.sh)

reports:
  checkstyle: true
  pmd: true
  findbugs: true
  junit: true

jenkins: &jenkins_config
  concurrentBuild: true
  maxConcurrentTotal: 8

pipelines:

  # prb builds
  - name: apple-1.9.1.x-spark-prb
    branchName: apple-1.9.1.x
    build:
      template: freestyle:v4:prb
      steps:
        - apple/spark-build.sh
    machine:
      baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
    jenkins: *jenkins_config

  - name: apple-1.9.1.x-release-spark-prb
    branchName: apple-1.9.1.x-release
    build:
      template: freestyle:v4:prb
      steps:
        - apple/spark-build.sh
    machine:
      baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
    jenkins: *jenkins_config

  - group: flink-prb-core
    machine:
      baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
    build:
      template: freestyle:v4:prb
      steps:
        - TARGET=core apple/flink-build.sh

  - group: flink-prb-1.18
    machine:
      baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
    build:
      template: freestyle:v4:prb
      steps:
        - TARGET=flink FLINK_VERSION=1.18 apple/flink-build.sh

  - group: flink-prb-1.19
    machine:
      baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
    build:
      template: freestyle:v4:prb
      steps:
        - TARGET=flink FLINK_VERSION=1.19 apple/flink-build.sh

  - group: flink-prb-1.20
    machine:
      baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
    build:
      template: freestyle:v4:prb
      steps:
        - TARGET=flink FLINK_VERSION=1.20 apple/flink-build.sh

  - group: flink-prb-2.1
    machine:
      baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
    build:
      template: freestyle:v4:prb
      steps:
        - TARGET=flink FLINK_VERSION=2.1 apple/flink-build.sh

  # publish pipelines
  - name: apple-1.9.1.x-scala-2.13-snapshot
    branchName: apple-1.9.1.x
    build:
      template: freestyle:v4:publish
      steps:
        - apple/spark-publish.sh
        - apple/flink-publish.sh
    package:
      freeform:
        - publish:
            - repo: m2:oss-patched
    finally:
      radar:
        annotate: true
    machine:
      baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
    jenkins: *jenkins_config

  - name: apple-1.9.1.x-scala-2.13-release
    branchName: apple-1.9.1.x-release
    build:
      template: freestyle:v4:publish
      steps:
        - apple/spark-release.sh
        - apple/flink-release.sh
    package:
      release: true
      freeform:
        - publish:
            - repo: m2:oss-patched
    finally:
      radar:
        annotate: true
    machine:
      baseImage: docker.apple.com/pie/comet-builder-ubi8:latest
    jenkins: *jenkins_config
