schemaVersion: 2.0
timeout: 120

notify:
  pullRequestComment:
    postOnSuccess: false

machine:
  env: &base_env
    skipTest: false
    CODE_VERSION: $(./code_version.sh)

reports:
  checkstyle: true
  pmd: true
  findbugs: true
  junit: true

pipelines:

# prb builds
- name: apple-0.13.x-prb-jdk8
  branchName: apple-0.13.x
  machine:
    env:
      <<: *base_env
      RUNTIME_JDK_VERSION: 8-applejdk
  build:
    template: buildozer:v4:prb

- name: apple-0.13.x-prb-jdk11
  branchName: apple-0.13.x
  machine:
    env:
      <<: *base_env
      RUNTIME_JDK_VERSION: 11
  build:
    template: buildozer:v4:prb

- name: apple-0.13.x-release-prb-jdk8
  branchName: apple-0.13.x-release
  machine:
    env:
      <<: *base_env
      RUNTIME_JDK_VERSION: 8-applejdk
  build:
    template: buildozer:v4:prb

- name: apple-0.13.x-release-prb-jdk11
  branchName: apple-0.13.x-release
  machine:
    env:
      <<: *base_env
      RUNTIME_JDK_VERSION: 11
  build:
    template: buildozer:v4:prb

# publish pipelines
- name: apple-0.13.x-publish-jdk11
  branchName: apple-0.13.x
  machine:
    env:
      <<: *base_env
      RUNTIME_JDK_VERSION: 11
  build:
    template: buildozer:v4:publish
  package:
    libraries:
    - publish:
      - repo: m2:oss-patched
  finally:
    radar:
      annotate: true

- name: apple-0.13.x-release-publish-jdk11
  branchName: apple-0.13.x-release
  machine:
    env:
      <<: *base_env
      RUNTIME_JDK_VERSION: 11
  build:
    template: buildozer:v4:publish
  package:
    release: true
    libraries:
    - publish:
      - repo: m2:oss-patched
  finally:
    radar:
      annotate: true
    tag:
      expression: ${CODE_VERSION}