schemaVersion: 2.0
timeout: 150

notify:
  pullRequestComment:
    postOnSuccess: false

machine:
  env:
    RUNTIME_JDK_VERSION: 11
    skipTest: false
    CODE_VERSION: $(./code_version.sh)

reports:
  checkstyle: true
  pmd: true
  findbugs: true
  junit: true

jenkins: &jenkins_config
  concurrentBuild: true
  maxConcurrentTotal: 8

pipelines:

# prb builds
- name: apple-1.3.0.x-scala-2.12-prb
  branchName: apple-1.3.0.x
  build:
    template: buildozer:v4:prb
  machine:
    baseImage: docker.apple.com/pie/boson:jdk11
  jenkins: *jenkins_config

- name: apple-1.3.0.x-scala-2.13-prb
  branchName: apple-1.3.0.x
  build:
    template: freestyle:v4:prb
    steps:
      - ./gradlew -DscalaVersion=2.13 :iceberg-spark:iceberg-spark-3.4_2.13:build :iceberg-spark:iceberg-spark-extensions-3.4_2.13:build :iceberg-spark:iceberg-spark-runtime-3.4_2.13:build
  machine:
    baseImage: docker.apple.com/pie/boson:jdk11
  jenkins: *jenkins_config

- name: apple-1.3.0.x-release-scala-2.12-prb
  branchName: apple-1.3.0.x-release
  build:
    template: buildozer:v4:prb
  machine:
    baseImage: docker.apple.com/pie/boson:jdk11
  jenkins: *jenkins_config

- name: apple-1.3.0.x-release-scala-2.13-prb
  branchName: apple-1.3.0.x-release
  build:
    template: freestyle:v4:prb
    steps:
      - ./gradlew -DscalaVersion=2.13 :iceberg-spark:iceberg-spark-3.4_2.13:build :iceberg-spark:iceberg-spark-extensions-3.4_2.13:build :iceberg-spark:iceberg-spark-runtime-3.4_2.13:build
  machine:
    baseImage: docker.apple.com/pie/boson:jdk11
  jenkins: *jenkins_config

# publish pipelines
- name: apple-1.3.0.x-scala-2.12-snapshot
  branchName: apple-1.3.0.x
  build:
    template: buildozer:v4:publish
  package:
    libraries:
    - publish:
      - repo: m2:oss-patched
  finally:
    radar:
      annotate: true
  machine:
    baseImage: docker.apple.com/pie/boson:jdk11
  jenkins: *jenkins_config

- name: apple-1.3.0.x-scala-2.13-snapshot
  branchName: apple-1.3.0.x
  build:
    template: freestyle:v4:publish
    steps:
      - ./gradlew -DscalaVersion=2.13 :iceberg-spark:iceberg-spark-3.4_2.13:build :iceberg-spark:iceberg-spark-extensions-3.4_2.13:build :iceberg-spark:iceberg-spark-runtime-3.4_2.13:build
      - home_dir=$(pwd)
      - ./gradlew -DscalaVersion=2.13 -Dmaven.repo.local=${home_dir}/local-repo :iceberg-spark:iceberg-spark-3.4_2.13:publishToMavenLocal :iceberg-spark:iceberg-spark-extensions-3.4_2.13:publishToMavenLocal :iceberg-spark:iceberg-spark-runtime-3.4_2.13:publishToMavenLocal
      - ci stage-lib --many-many-artifacts "./local-repo/**/*.jar"
      - ci stage-lib --many-many-artifacts "./local-repo/**/*.pom"
  package:
    freeform:
    - publish:
      - repo: m2:oss-patched
  finally:
    radar:
      annotate: true
  machine:
    baseImage: docker.apple.com/pie/boson:jdk11
  jenkins: *jenkins_config

- name: apple-1.3.0.x-scala-2.12-release
  branchName: apple-1.3.0.x-release
  build:
    template: buildozer:v4:publish
  package:
    release: true
    libraries:
    - publish:
      - repo: m2:oss-patched
  finally:
    radar:
      annotate: true
    tag:
      expression: ${CODE_VERSION}
  machine:
    baseImage: docker.apple.com/pie/boson:jdk11
  jenkins: *jenkins_config

- name: apple-1.3.0.x-scala-2.13-release
  branchName: apple-1.3.0.x-release
  build:
    template: freestyle:v4:publish
    steps:
      - ./gradlew -DscalaVersion=2.13 :iceberg-spark:iceberg-spark-3.4_2.13:build :iceberg-spark:iceberg-spark-extensions-3.4_2.13:build :iceberg-spark:iceberg-spark-runtime-3.4_2.13:build
      - home_dir=$(pwd)
      - ./gradlew -Priorelease -DscalaVersion=2.13 -Dmaven.repo.local=${home_dir}/local-repo :iceberg-spark:iceberg-spark-3.4_2.13:publishToMavenLocal :iceberg-spark:iceberg-spark-extensions-3.4_2.13:publishToMavenLocal :iceberg-spark:iceberg-spark-runtime-3.4_2.13:publishToMavenLocal
      - ci stage-lib --many-many-artifacts "./local-repo/**/*.jar"
      - ci stage-lib --many-many-artifacts "./local-repo/**/*.pom"
  package:
    release: true
    freeform:
      - publish:
          - repo: m2:oss-patched
  finally:
    radar:
      annotate: true
  machine:
    baseImage: docker.apple.com/pie/boson:jdk11
  jenkins: *jenkins_config

# publish pr pipelines
- group: pr-build
  branchName: feature/comet
  version: start
  name: pr-build-start
  machine:
    baseImage: docker.apple.com/pie/boson:jdk11
  build:
    template: freestyle:v4:build
    buildParameters:
      - parameter: PR_NUMBER
        description: The source pull request to benchmark
    steps: [ "true" ]
  reports:
    checkstyle: false
    pmd: false
    findbugs: false
    junit: false
  finally:
    pipelineChain:
      - pipeline: pr-build-apple-scala-2.12-snapshot
        buildArguments:
          - name: "PR_NUMBER"
            value: "${BUILD_PARAM_PR_NUMBER}"
      - pipeline: pr-build-apple-scala-2.13-snapshot
        buildArguments:
          - name: "PR_NUMBER"
            value: "${BUILD_PARAM_PR_NUMBER}"

- name: pr-build-apple-scala-2.12-snapshot
  group: pr-build
  branchName: feature/comet
  machine:
    baseImage: docker.apple.com/pie/boson:jdk11
  build:
    template: freestyle:v4:publish
    buildParameters:
      - parameter: PR_NUMBER
        description: The source pull request to benchmark
    steps:
      # Switch to PR
      - set -e
      - set -x
      - git fetch --force -q origin pull/${BUILD_PARAM_PR_NUMBER}/head:pr_${BUILD_PARAM_PR_NUMBER}
      - git checkout pr_${BUILD_PARAM_PR_NUMBER}
      - git log -n 1
      
      # Switch to PR version
      - CODE_VERSION=$(./code_version.sh | sed "s/-apple/-apple-pr${BUILD_PARAM_PR_NUMBER}-SNAPSHOT/")
      - echo $CODE_VERSION > version.txt

      - home_dir=$(pwd)
      - ./gradlew -Dmaven.repo.local=${home_dir}/local-repo publishToMavenLocal
      - ci stage-lib --many-many-artifacts "./local-repo/**/*.jar"
      - ci stage-lib --many-many-artifacts "./local-repo/**/*.pom"
  reports:
    checkstyle: false
    pmd: false
    findbugs: false
    junit: false
  package:
    freeform:
    - publish:
      - repo: m2:oss-patched
  machine:
    baseImage: docker.apple.com/pie/boson:jdk11
  jenkins: *jenkins_config
  finally:
    pipelineChain:
      - pipeline: pr-build-apple-scala-2.13-snapshot
        buildArguments:
          - name: "PR_NUMBER"
            value: "${BUILD_PARAM_PR_NUMBER}"

- name: pr-build-apple-scala-2.13-snapshot
  group: pr-build
  branchName: feature/comet
  machine:
    baseImage: docker.apple.com/pie/boson:jdk11
  build:
    template: freestyle:v4:publish
    buildParameters:
      - parameter: PR_NUMBER
        description: The source pull request to benchmark
    steps:
      # Switch to PR
      - set -e
      - set -x
      - git fetch --force -q origin pull/${BUILD_PARAM_PR_NUMBER}/head:pr_${BUILD_PARAM_PR_NUMBER}
      - git checkout pr_${BUILD_PARAM_PR_NUMBER}
      - git log -n 1
     
      # Switch to PR version
      - CODE_VERSION=$(./code_version.sh | sed "s/-apple/-apple-pr${BUILD_PARAM_PR_NUMBER}-SNAPSHOT/")
      - echo $CODE_VERSION > version.txt

      #- ./gradlew -DscalaVersion=2.13 :iceberg-spark:iceberg-spark-3.4_2.13:build :iceberg-spark:iceberg-spark-extensions-3.4_2.13:build :iceberg-spark:iceberg-spark-runtime-3.4_2.13:build
      - home_dir=$(pwd)
      #- ./gradlew -DscalaVersion=2.13 -Dmaven.repo.local=${home_dir}/local-repo :iceberg-spark:iceberg-spark-3.4_2.13:publishToMavenLocal :iceberg-spark:iceberg-spark-extensions-3.4_2.13:publishToMavenLocal :iceberg-spark:iceberg-spark-runtime-3.4_2.13:publishToMavenLocal
      - ./gradlew -DscalaVersion=2.13 -Dmaven.repo.local=${home_dir}/local-repo :iceberg-spark:iceberg-spark-3.4_2.13:publishToMavenLocal :iceberg-spark:iceberg-spark-extensions-3.4_2.13:publishToMavenLocal :iceberg-spark:iceberg-spark-runtime-3.4_2.13:publishToMavenLocal
      - ci stage-lib --many-many-artifacts "./local-repo/**/*.jar"
      - ci stage-lib --many-many-artifacts "./local-repo/**/*.pom"
  reports:
    checkstyle: false
    pmd: false
    findbugs: false
    junit: false
  package:
    freeform:
    - publish:
      - repo: m2:oss-patched
  machine:
    baseImage: docker.apple.com/pie/boson:jdk11
  jenkins: *jenkins_config
