#!/usr/bin/env bash

set -e

# TARGET can be "core", "flink", "all"
TARGET="${TARGET:-all}"
# Which Flink version to build, e.g. 2.1
FLINK_VERSION="${FLINK_VERSION:-}"

GRADLE_ARGS="${GRADLE_ARGS:-}"
BUILD_ARGS="${BUILD_ARGS:-}"
BUILD_ARGS+=" -Dorg.gradle.jvmargs=-Xmx4G"

build_core() {
  echo "Building core dependencies"
  # Modules flink depends on
  # Generated by:
  #   ./gradlew iceberg-flink:iceberg-flink-runtime-1.19:dependencies >/tmp/dep
  #   for i in `grep iceberg /tmp/dep|cut -d ':' -f 2|sort|uniq|grep -v '\*'|grep -v project`;do echo -n ":${i}:build ";done
  ./gradlew ${GRADLE_ARGS} :iceberg-aliyun:build :iceberg-api:build :iceberg-aws:build :iceberg-azure:build :iceberg-bundled-guava:build :iceberg-common:build :iceberg-core:build :iceberg-data:build :iceberg-flink:build :iceberg-gcp:build :iceberg-hive-metastore:build :iceberg-nessie:build :iceberg-orc:build :iceberg-parquet:build
}

build_flink() {
  if [[ "${FLINK_VERSION}" == "" ]]; then
    echo "Please specify a Flink version via FLINK_VERSION, e.g. FLINK_VERSION=2.1"
    exit 1;
  fi
  echo "Building Flink modules for Flink ${FLINK_VERSION}"
  # The build and test of the flink jars
  ./gradlew ${GRADLE_ARGS} :iceberg-flink:iceberg-flink-${FLINK_VERSION}:test ${BUILD_ARGS}
  # The build and test of the runtime jars
  ./gradlew ${GRADLE_ARGS} :iceberg-flink:iceberg-flink-runtime-${FLINK_VERSION}:build ${BUILD_ARGS}
}

if [[ "$TARGET" == "all" ]]; then
  build_core
  build_flink
elif [[ "$TARGET" == "core" ]]; then
  build_core
elif [[ "$TARGET" == "flink" ]]; then
  build_flink
else
  echo "Invalid target '${TARGET}'"
  exit 1;
fi
