#!/usr/bin/env bash
set -e

HOME_DIR=$(pwd)
if [ -z "${RELEASE}" ]
then
      RELEASE_BUILD=""
else
      RELEASE_BUILD="-PreleaseBuild=true"
fi

if [[ "${PUBLISH_TO_M2_LOCAL}" == "true" ]]; then
    MAVEN_REPO_ARG=""
else
    MAVEN_REPO_ARG="-Dmaven.repo.local=${HOME_DIR}/local-repo"
fi

echo "Using parameters ${RELEASE_BUILD} based on input ${RELEASE}. PUBLISH_TO_M2_LOCAL=${PUBLISH_TO_M2_LOCAL}, MAVEN_REPO_ARG=${MAVEN_REPO_ARG}"

# Publish the jars to a local repo
# Modules flink depends on
# Generated by:
#   ./gradlew iceberg-flink:iceberg-flink-runtime-1.19:dependencies >/tmp/dep
#   for i in `grep iceberg /tmp/dep|cut -d ':' -f 2|sort|uniq|grep -v '\*'|grep -v project`;do echo -n ":${i}:publishToMavenLocal ";done
./gradlew ${RELEASE_BUILD} ${MAVEN_REPO_ARG} :iceberg-aliyun:publishToMavenLocal :iceberg-api:publishToMavenLocal :iceberg-aws:publishToMavenLocal :iceberg-azure:publishToMavenLocal :iceberg-bundled-guava:publishToMavenLocal :iceberg-common:publishToMavenLocal :iceberg-core:publishToMavenLocal :iceberg-data:publishToMavenLocal :iceberg-flink:publishToMavenLocal :iceberg-gcp:publishToMavenLocal :iceberg-hive-metastore:publishToMavenLocal :iceberg-nessie:publishToMavenLocal :iceberg-orc:publishToMavenLocal :iceberg-parquet:publishToMavenLocal
# Publish the flink jars to a local repo
./gradlew ${RELEASE_BUILD} ${MAVEN_REPO_ARG} :iceberg-flink:iceberg-flink-2.0:publishToMavenLocal :iceberg-flink:iceberg-flink-1.20:publishToMavenLocal :iceberg-flink:iceberg-flink-1.19:publishToMavenLocal :iceberg-flink:iceberg-flink-1.18:publishToMavenLocal
# Publish the runtime jars to a local repo
./gradlew ${RELEASE_BUILD} ${MAVEN_REPO_ARG} :iceberg-flink:iceberg-flink-runtime-2.0:publishToMavenLocal :iceberg-flink:iceberg-flink-runtime-1.20:publishToMavenLocal :iceberg-flink:iceberg-flink-runtime-1.19:publishToMavenLocal :iceberg-flink:iceberg-flink-runtime-1.18:publishToMavenLocal
# Publish the jars for the local repo

if [[ "${PUBLISH_TO_M2_LOCAL}" != "true" ]]; then
   ci stage-lib --many-many-artifacts "./local-repo/**/*.jar"
   ci stage-lib --many-many-artifacts "./local-repo/**/*.pom"
fi
