#!/usr/bin/env bash

set -e

GRADLE_ARGS="${GRADLE_ARGS:-}"
BUILD_ARGS="${BUILD_ARGS:-}"
BUILD_ARGS+=" -Dorg.gradle.jvmargs=-Xmx4G"

# Build Spark-specific core dependencies and Spark modules
# Spark dependencies generated by:
#   ./gradlew :iceberg-spark:iceberg-spark-runtime-4.0_2.13:dependencies >/tmp/spark_dep && cat /tmp/spark_dep | grep iceberg | cut -d ':' -f 2 | sort | uniq | grep -v '\*' | grep -v project | while read module; do echo -n ":${module}:build "; done
./gradlew ${GRADLE_ARGS} \
  :iceberg-aliyun:build \
  :iceberg-api:build \
  :iceberg-arrow:build \
  :iceberg-aws:build \
  :iceberg-azure:build \
  :iceberg-bundled-guava:build \
  :iceberg-common:build \
  :iceberg-core:build \
  :iceberg-data:build \
  :iceberg-gcp:build \
  :iceberg-hive-metastore:build \
  :iceberg-nessie:build \
  :iceberg-open-api:build \
  :iceberg-orc:build \
  :iceberg-parquet:build \
  :iceberg-snowflake:build \
  ${BUILD_ARGS}

# Build and test Spark modules
./gradlew ${GRADLE_ARGS} \
  -DscalaVersion=2.13 \
  :iceberg-spark:iceberg-spark-4.0_2.13:build \
  :iceberg-spark:iceberg-spark-extensions-4.0_2.13:build \
  :iceberg-spark:iceberg-spark-runtime-4.0_2.13:build \
  ${BUILD_ARGS}